name: coding_challenge_weather
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  animation_search_bar: ^0.0.10
  animations: ^2.0.8
  confetti: ^0.7.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_carousel_slider: ^1.1.0
  flutter_riverpod: ^2.4.5
  flutter_svg: ^2.0.9
  geolocator: ^10.1.0
  google_fonts: ^6.1.0
  http: ^1.1.0
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  riverpod_annotation: ^2.3.0
  envied: ^0.3.0+3
  dart_openai: ^4.1.4
  fl_chart: ^0.64.0

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.6
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  riverpod_generator: ^2.3.5
  envied_generator: ^0.3.0+3
  # riverpod_lint: ^2.3.3

dependency_overrides:
  envied:
    git:
      url: https://github.com/petercinibulk/envied
      ref: 0d08946199a7d50677cabee816296130d75bad99
      path: packages/envied/
  envied_generator:
    git:
      url: https://github.com/petercinibulk/envied
      ref: 0d08946199a7d50677cabee816296130d75bad99
      path: packages/envied_generator/

flutter:
  uses-material-design: true

  assets:
    - assets/icons/svg-static/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
